Create minimal .travis.yml to fix bundler error
Travis CI error when submitting pull request:
  NoMethodError: undefined method `spec' for nil:NilClass
may be caused by outdated bundler